runtime: python38

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  DB_CONNECTION_NAME: pristine-skein-289822:us-central1:brokenlapotops
  DB_USER: root
  DB_PASS: 71j1vGDvrz7IfJD2
  DB_NAME: brokenlaptops   
